{
    "openapi": "3.0.0",
    "info": {
        "title": "Swagger with Laravel",
        "version": "1.0.0"
    },
    "paths": {
        "/api/getForm/": {
            "get": {
                "tags": [
                    "form"
                ],
                "summary": "getForm",
                "description": "getForm Endpoint",
                "operationId": "getForm",
                "parameters": [
                    {
                        "name": "step",
                        "in": "query",
                        "description": "step for form",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "form data",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "formData": [],
                                                "step": 1,
                                                "type": "needRequired|allowedNewStep"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/saveForm/": {
            "post": {
                "tags": [
                    "form"
                ],
                "summary": "saveForm",
                "description": "saveForm Endpoint",
                "operationId": "saveForm",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "step"
                                ],
                                "properties": {
                                    "step": {
                                        "type": "number"
                                    },
                                    "formData": {
                                        "type": "json"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "save form",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "step": 1,
                                                "type": "needRequired|allowedNewStep|addedNewFields"
                                            }
                                        }
                                    },
                                    "result error": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле step обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/saveFile/": {
            "post": {
                "tags": [
                    "form"
                ],
                "summary": "saveFile",
                "description": "saveFile Endpoint",
                "operationId": "saveFile",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file[]"
                                ],
                                "properties": {
                                    "file[]": {
                                        "type": "array",
                                        "items": {
                                            "type": "file"
                                        }
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "file info",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "resFile": "url file"
                                        }
                                    },
                                    "result error": {
                                        "summary": "Ошибка формирования файла",
                                        "value": {
                                            "status": "error",
                                            "error": "Текст"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/saveUserImg/": {
            "post": {
                "tags": [
                    "form"
                ],
                "summary": "saveUserImg",
                "description": "saveUserImg Endpoint",
                "operationId": "saveUserImg",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "properties": {
                                    "file": {
                                        "type": "file"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "file  info",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "resFile": "url file"
                                        }
                                    },
                                    "error": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Ничего не загружено"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/finishRegister/": {
            "get": {
                "tags": [
                    "form"
                ],
                "summary": "finishRegister",
                "description": "finishRegister Endpoint",
                "operationId": "finishRegister",
                "responses": {
                    "200": {
                        "description": "finish register",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/sendPhone/": {
            "post": {
                "tags": [
                    "register/auth"
                ],
                "summary": "sendPhone",
                "description": "sendPhone Endpoint",
                "operationId": "sendPhone",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "send phone start register or auth",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "type": "auth|register",
                                                "code": {
                                                    "status": "exists|success",
                                                    "ttl": "120 числовое поле если статус exists",
                                                    "code": "sms код для теста"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "phone is empty or error code",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле телефон обязательна для заполнения"
                                        }
                                    },
                                    "error result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "error",
                                            "result": {
                                                "type": "auth|register",
                                                "code": {
                                                    "status": "errorSend"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/checkCode/": {
            "post": {
                "tags": [
                    "register/auth"
                ],
                "summary": "checkCode",
                "description": "checkCode Endpoint",
                "operationId": "checkCode",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone",
                                    "code"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "number"
                                    },
                                    "code": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "check sms code success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    },
                                    "result error": {
                                        "summary": "Ошибка",
                                        "value": {
                                            "status": "error",
                                            "result": {
                                                "code": {
                                                    "status": "error|notExists"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "phone or code is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result code": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле код обязательна для заполнения"
                                        }
                                    },
                                    "result phone": {
                                        "summary": "Ошибка телефона",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле телефон обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/setUserPin/": {
            "post": {
                "tags": [
                    "register/auth"
                ],
                "summary": "setUserPin",
                "description": "setUserPin Endpoint",
                "operationId": "setUserPin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "pin"
                                ],
                                "properties": {
                                    "pin": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "set pin success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "pin is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result pin": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле пин код обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/startRestorePin/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "startRestorePin",
                "description": "startRestorePin Endpoint",
                "operationId": "startRestorePin",
                "responses": {
                    "200": {
                        "description": "send phone start register or auth",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "code": {
                                                    "status": "exists|success",
                                                    "ttl": "120 числовое поле если статус exists",
                                                    "code": "sms код для теста"
                                                },
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/checkCodeRestore/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "checkCodeRestore",
                "description": "checkCodeRestore Endpoint",
                "operationId": "checkCodeRestore",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "code"
                                ],
                                "properties": {
                                    "code": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "check sms code success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    },
                                    "result error": {
                                        "summary": "Ошибка",
                                        "value": {
                                            "status": "error",
                                            "result": {
                                                "code": {
                                                    "status": "error|notExists"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "phone or code is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result code": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле код обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/checkPin/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "checkPin",
                "description": "checkPin Endpoint",
                "operationId": "checkPin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "pin"
                                ],
                                "properties": {
                                    "pin": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "check pin code",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    },
                                    "result check pin error": {
                                        "summary": "Неверный пин",
                                        "value": {
                                            "status": "error"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "pin is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result pin": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле пин обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/refreshToken/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "refreshToken",
                "description": "refreshToken Endpoint",
                "operationId": "refreshToken",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "refreshToken"
                                ],
                                "properties": {
                                    "refreshToken": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "refresh token success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "success refresh token": {
                                        "summary": "Успешное востановление",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "token_type": "Bearer",
                                                    "expires_in": "числовое значение в секундах время жизни access_token",
                                                    "access_token": "токен доступа",
                                                    "refresh_token": "токен восстановления access_token"
                                                }
                                            }
                                        }
                                    },
                                    "error refresh token": {
                                        "summary": "Неуспешное востановление",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "token": {
                                                    "error": "invalid_request",
                                                    "error_description": "The refresh token is invalid.",
                                                    "hint": "Token is not linked to client",
                                                    "message": "The refresh token is invalid."
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "refreshToken is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result refreshToken": {
                                        "summary": "Ошибка токена",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле refreshToken обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/getUserInfo/": {
            "get": {
                "tags": [
                    "Personal area"
                ],
                "summary": "getForm",
                "description": "getUserInfo Endpoint",
                "operationId": "getUserInfo",
                "responses": {
                    "200": {
                        "description": "uset info",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "userData": []
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/getUserFields/": {
            "get": {
                "tags": [
                    "Personal area"
                ],
                "summary": "getForm",
                "description": "getForm",
                "operationId": "getUserFields",
                "responses": {
                    "200": {
                        "description": "form data",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "formData": [],
                                                "section": [],
                                                "type": "needRequired|allowedNewStep"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/getUserPersonalMenu/": {
            "get": {
                "tags": [
                    "Personal area"
                ],
                "summary": "getUserPersonalMenu",
                "description": "getUserPersonalMenu",
                "operationId": "getUserPersonalMenu",
                "responses": {
                    "200": {
                        "description": "menu data",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "section": []
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/saveUserFields/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "saveUserFields",
                "description": "saveUserFields Endpoint",
                "operationId": "saveUserFields",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "formData"
                                ],
                                "properties": {
                                    "formData": {
                                        "type": "json"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "save form",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "formData is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result formData": {
                                        "summary": "Ошибка formData",
                                        "value": {
                                            "status": "error",
                                            "error": "Ничего не загружено"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/saveUserImg/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "saveUserImgPersonal",
                "description": "saveUserImgPersonal Endpoint",
                "operationId": "saveUserImgPersonal",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "properties": {
                                    "file": {
                                        "type": "file"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "file  info",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success",
                                            "resFile": "url file"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "file is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "error": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Ничего не загружено"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/setUserEmail/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "setUserEmail",
                "description": "setUserEmail Endpoint",
                "operationId": "setUserEmail",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "send email for verified",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "code": {
                                                    "status": "exists|success",
                                                    "ttl": "120 числовое поле если статус exists",
                                                    "code": "sms код для теста"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "email is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Нехватка полей",
                                        "value": {
                                            "status": "error",
                                            "error": "Email отсутствует"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/checkEmailCode/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "checkEmailCode",
                "description": "checkEmailCode Endpoint",
                "operationId": "checkEmailCode",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "code"
                                ],
                                "properties": {
                                    "code": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "check email code success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успех",
                                        "value": {
                                            "status": "success"
                                        }
                                    },
                                    "result error": {
                                        "summary": "Ошибка",
                                        "value": {
                                            "status": "error",
                                            "result": {
                                                "code": {
                                                    "status": "error|notExists"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "Code is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result code": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле код обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/changeUserPhone/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "changeUserPhone",
                "description": "changeUserPhone Endpoint",
                "operationId": "changeUserPhone",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "start change phone",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "success",
                                            "result": {
                                                "code": {
                                                    "status": "exists|success",
                                                    "ttl": "120 числовое поле если статус exists",
                                                    "code": "sms код для теста"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "phone is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result phone": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле телефон обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/personal/confirmChangeUserPhone/": {
            "post": {
                "tags": [
                    "Personal area"
                ],
                "summary": "confirmChangeUserPhone",
                "description": "confirmChangeUserPhone Endpoint",
                "operationId": "confirmChangeUserPhone",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "phone",
                                    "code"
                                ],
                                "properties": {
                                    "phone": {
                                        "type": "number"
                                    },
                                    "code": {
                                        "type": "number"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "confirm or error change phone",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Успешный запрос",
                                        "value": {
                                            "status": "success"
                                        }
                                    },
                                    "result error": {
                                        "summary": "Ошибка",
                                        "value": {
                                            "status": "error",
                                            "result": {
                                                "code": {
                                                    "status": "error|notExists"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "417": {
                        "description": "Code or phone is empty",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result phone": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле телефон обязательна для заполнения"
                                        }
                                    },
                                    "result code": {
                                        "summary": "Ошибка кода",
                                        "value": {
                                            "status": "error",
                                            "error": "Поле код обязательна для заполнения"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "passport": {
                "type": "oauth2",
                "description": "Laravel passport oauth2 security.",
                "in": "header",
                "scheme": "https",
                "flows": {
                    "password": {
                        "authorizationUrl": "http://preprod.marriator-api.fivecorners.ru/oauth/authorize",
                        "tokenUrl": "http://preprod.marriator-api.fivecorners.ru/oauth/token",
                        "refreshUrl": "http://preprod.marriator-api.fivecorners.ru/token/refresh",
                        "scopes": []
                    }
                }
            }
        }
    }
}